//! API Keys Management
//! 
//! Securely stores and loads API keys from local encrypted storage

use std::path::PathBuf;
use std::fs;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct ApiKeys {
    pub google_api_key: String,
    #[serde(default)]
    pub groq_api_key: String,
    #[serde(default)]
    pub nvidia_api_key: String,
    pub assembly_ai_key: String,
    #[serde(default)]
    pub screenshot_api_key: String,  // Optional, can use google_api_key
}

impl ApiKeys {
    pub fn is_complete(&self) -> bool {
        !self.assembly_ai_key.is_empty() && (!self.google_api_key.is_empty() || !self.groq_api_key.is_empty())
    }
}

/// Check if API keys are configured
pub fn are_api_keys_configured() -> bool {
    load_api_keys().map(|k| k.is_complete()).unwrap_or(false)
}

/// Load API keys from secure storage
pub fn load_api_keys() -> Option<ApiKeys> {
    let path = get_api_keys_path();
    let encoded = fs::read_to_string(&path).ok()?;
    let decoded = base64::decode(encoded.trim()).ok()?;
    let json = String::from_utf8(decoded).ok()?;
    let mut keys: ApiKeys = serde_json::from_str(&json).ok()?;
    
    // Use google_api_key for screenshot if not set
    if keys.screenshot_api_key.is_empty() {
        keys.screenshot_api_key = keys.google_api_key.clone();
    }
    
    Some(keys)
}

/// Save API keys to secure storage
pub fn save_api_keys(keys: &ApiKeys) -> Result<(), String> {
    let path = get_api_keys_path();
    
    // Create directory if needed
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|e| format!("Failed to create config dir: {}", e))?;
    }
    
    // Encode (base64 for basic protection)
    let json = serde_json::to_string(keys).map_err(|e| format!("Failed to serialize: {}", e))?;
    let encoded = base64::encode(json.as_bytes());
    
    fs::write(&path, encoded).map_err(|e| format!("Failed to save API keys: {}", e))?;
    
    // Also write to .env for backward compatibility
    write_env_file(keys)?;
    
    Ok(())
}

/// Write .env file for backward compatibility
fn write_env_file(keys: &ApiKeys) -> Result<(), String> {
    let exe_path = std::env::current_exe().map_err(|e| e.to_string())?;
    let exe_dir = exe_path.parent().ok_or("No parent dir")?;
    let env_path = exe_dir.join(".env");
    
    let content = format!(
        "# Auto-generated by Interview Helper\n\
        GOOGLE_API_KEY={}\n\
        GROQ_API_KEY={}\n\
        NVIDIA_API_KEY={}\n\
        ASSEMBLY_AI_KEY={}\n\
        SCREENSHOT_API_KEY={}\n",
        keys.google_api_key,
        keys.groq_api_key,
        keys.nvidia_api_key,
        keys.assembly_ai_key,
        if keys.screenshot_api_key.is_empty() { &keys.google_api_key } else { &keys.screenshot_api_key }
    );
    
    fs::write(&env_path, content).map_err(|e| format!("Failed to write .env: {}", e))?;
    
    Ok(())
}

/// Get API keys file path
fn get_api_keys_path() -> PathBuf {
    let mut path = dirs_next::data_local_dir()
        .unwrap_or_else(|| PathBuf::from("."));
    path.push("InterviewHelper");
    path.push(".apikeys");
    path
}
