[package]
name = "frontend"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"
default-run = "frontend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "frontend_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
windows = { version = "0.52", features = [
    "Win32_Foundation",
    "Win32_System_Threading",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_System_LibraryLoader",
    "Win32_System_Diagnostics_ToolHelp",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Kernel",
    "Win32_System_Memory",
    "Win32_System_Console",
    "Win32_System_Registry",
    "Win32_Storage_FileSystem",
    "Win32_UI_Shell",
    "Win32_System_Services",
    "Win32_System_SystemServices",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_Security",
    "Win32_Media_Audio",
    "Win32_System_DataExchange",
    "Win32_Graphics_Gdi",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Graphics_Direct3D11",
    "Win32_Graphics_Direct3D",
] }
tokio-tungstenite = { version = "0.21", features = ["native-tls"] }
tokio = { version = "1.36", features = ["full"] }
futures-util = "0.3"
anyhow = "1.0"
log = "0.4"
env_logger = "0.11"
image = "0.24"
reqwest = { version = "0.11", features = ["json", "stream", "blocking"] } 
lazy_static = "1.4"
chrono = "0.4"
base64 = "0.21"
rand = "0.8"
ntapi = "0.4"
dotenv = "0.15"
cpal = "0.15"
hound = "3.5"
http = "1.0"
dirs-next = "2.0"
window-vibrancy = "0.5"
